const projectsDetails = [
  {
    _id: 1,
    projectImg: "ShazaibTechnologies.webp",
    projectTitle: "Shazaib Technologies",
    projectDes: "Shazaib Technologies is an eCommerce website built with HTML, CSS, and TailwindCSS.",
    liveProjectCheckContent: "Check Live Site",
    liveProjectCheckUrl: "https://shazaib-technologies.vercel.app/",
  },
  {
    _id: 2,
    projectImg:"WeatherApp.png",
    projectTitle: "Weather App",
    projectDes: "A real-time climate tracking app developed with HTML, CSS, and JavaScript.",
    liveProjectCheckContent: "Check Live Site",
    liveProjectCheckUrl: "https://real-time-weather-app-5w4h-nu0md7xfg-javeriachs-projects.vercel.app/",
  },
  {
    _id: 3,
    projectImg: "QuranApp.png",
    projectTitle: "Quran App",
    projectDes: "Quran App built with HTML, CSS, and JavaScript to browse and read Quranic verses.",
    liveProjectCheckContent: "Check Live Site",
    liveProjectCheckUrl: "https://quran-app-b7kk.vercel.app/",
  },
  {
    _id: 4,
    projectImg: "ImageGallery.png",
    projectTitle: "Image Gallery",
    projectDes: "An interactive image gallery using HTML, CSS, and JavaScript.",
    liveProjectCheckContent: "Check Live Site",
    liveProjectCheckUrl: "https://image-gallery-rosy.vercel.app/",
  },
  {
    _id: 5,
    projectImg: "PasswordGenerater.png",
    projectTitle: "Password Generator",
    projectDes: "Secure password generator made with HTML, CSS, and JavaScript.",
    liveProjectCheckContent: "Check Live Site",
    liveProjectCheckUrl: "https://random-password-generator-delta.vercel.app/",
  },
  {
    _id: 6,
    projectImg: "TaskTracker.png",
    projectTitle: "Task Tracker",
    projectDes: "A task management tool built with HTML, CSS, and JavaScript.",
    liveProjectCheckContent: "Check Live Site",
    liveProjectCheckUrl: "https://task-tracker-2v62.vercel.app/",
  },
  {
    _id: 7,
    projectImg: "TriaviaMaster.png",
    projectTitle: "Trivia Master",
    projectDes: "Trivia quiz game built with React.js, HTML, CSS, and JavaScript.",
    liveProjectCheckContent: "Check Live Site",
    liveProjectCheckUrl: "https://triavia-master-g5vt.vercel.app/",
  },
  {
    _id: 8,
    projectImg: "Tenzies.png",
    projectTitle: "Tenzies",
    projectDes: "Tenzies game developed with React.js, HTML, CSS, and JavaScript.",
    liveProjectCheckContent: "Check Live Site",
    liveProjectCheckUrl: "https://tenzies-alpha-livid.vercel.app/",
  },
  {
    _id: 9,
    projectImg: "MovieWorld.png",
    projectTitle: "Movie World",
    projectDes: "A movie browsing website built with React.js, HTML, CSS, and JavaScript.",
    liveProjectCheckContent: "Check Live Site",
    liveProjectCheckUrl: "https://movie-world-jcad.vercel.app/",
  },
  // {
  //   _id: 10,
  //   projectImg: "Tinder.webp",
  //   projectTitle: "Tinder Clone",
  //   projectDes: "Tinder clone built using MERN stack with Websockets for real-time interaction.",
  //   liveProjectCheckContent: "Check Live Site",
  //   liveProjectCheckUrl: "http://13.53.200.209/",
  // },
  // {
  //   _id: 11,
  //   projectImg: "Ecommerce.png",
  //   projectTitle: "EShop",
  //   projectDes: "Ecommerce platform using MERN stack with responsive UI and product management.",
  //   liveProjectCheckContent: "Check Live Site",
  //   liveProjectCheckUrl: "http://13.49.246.169/",
  // },
];

projectsDetails.reverse();

export default projectsDetails;
